apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: project
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server
  name: server
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
      - image: sergioarmgpl/server-proj
        name: server-proj
        env:
        - name: REDIS_SERVER
          value: "YOUR_REDIS_SERVER:6379"
        - name: REDIS_PASSWORD
          value: "YOUR_REDIS_PASSWORD"
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: server
    mirror.linkerd.io/exported: "true"
  name: server
  namespace: project
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: server
  type: ClusterIP
status:
  loadBalancer: {}